---
id: create-X-for-Y-discount-promotion
title: Create X for Y Discount Promotion
sidebar_label: Create X for Y Discount Promotion
---

## `POST` Create X for Y Discount Promotion

```http
https://api.moltin.com/v2/promotions/
```

:::note
Line-item discounts are only supported by the line calculation method. For more information about this method, see the [Calculation Method](../advanced/settings/index.md#calculation-method) section.
:::

## Parameters

### Headers

| Name | Required | Type | Description |
| --- | --- | --- | --- |
| `Authorization` | Required | `string` | The Bearer token required to get access to the API. |

### Body

 | Name | Required | Type | Description |
 | --- | --- | --- | --- |
 | `type` | Required | `string` | Specifies the type of the resource. The type of resource for promotions is, `promotion`. |
 | `name` | Required | `string` | Specifies a name for the promotion. |
 | `description` | Required | `string` | Specifies a description for the promotion. |
 | `enabled` | Required | `boolean` | Specifies whether the promotion is enabled. The options are `true` or `false`, and the default setting is `false`. |
 | `automatic` | Required  | `boolean` | Specifies whether the promotion is applied automatically to the cart or a code is required to apply the promotion. The default setting is `false`. When this value is set `true`, a code is autogenerated. If this value is set `false`, you must create the code manually. For more information about creating codes, see the [Create Promotion Codes](create-promotion-codes.md) section.|
 |`promotion_type`|Required  |`string`| Specifies the type of the promotion. Use `x_for_y` for creating X for Y discount promotions.|
 |`max_applications_per_cart`| Optional  |`integer` | Specifies the maximum number of application of a promotion per cart.|
 |`min_cart_value`| Optional  |`array`| Specifies an array of currency-value objects, `min_cart_value[].currency` and `min_cart_value[].amount`, that provide the minimum cart value required for the promotion to apply. You can add one or several value specifications in different currencies.|
 |`schema`|Required |`object`| Specifies the X and Y values for the promotion. For example, for a promotion 3 for 2, X is 3 and Y is 2. You must also provide the SKUs of all products included in this promotion.  |
 |`start`| Required  |`string`| Specifies the start date and time of the promotion or the start date of the promotion. You can provide a specific time in the HH:MM format. For example, `"start": "2000-01-01 12:00"`. If no time is specified, the default start and end time is set to `00:00`.|
 |`end`| Required  |`string`| Specifies the end date and time of the promotion or the end date of the promotion.|

## Request Example - Curl

 ```bash
 curl -X POST https://api.moltin.com/v2/promotions \
      -H "Authorization: Bearer 68302a5f3742875fbc647a20186a1b8932cad231' \
      -H 'accept: application/json' \
      -H 'content-type: application/json' \
      -H 'x-moltin-auth-store: {{storeID}}' \
      --data-raw '{
     "data": {
       "type": "promotion",
       "name": "X for Y promotion example",
       "description": "2 for 1 promotion for SKU1",
       "enabled": true,
       "automatic": true,
       "promotion_type": "x_for_y",
       "max_applications_per_cart":1,
       "schema": {
         "x": 2,
         "y": 1,
         "targets": [
           "SKU1"
         ]
       },
       "start": "2000-01-01",
       "end": "2100-01-01"
     }
   }'
 ```

### Response

`201 Created`

```json
{
    "data": {
        "type": "promotion",
        "id": "ffec5327-9180-4a83-bfd5-73ebacee8eed",
        "name": "X for Y promotion example",
        "description": "2 for 1 promotion for SKU1",
        "enabled": true,
        "automatic": true,
        "promotion_type": "x_for_y",
        "max_applications_per_cart":1,
        "schema": {
            "x": 2,
            "y": 1,
            "targets": [
                "SKU1"
            ]
        },
        "start": "2000-01-01T00:00:00Z",
        "end": "2100-01-01T00:00:00Z",
        "meta": {
            "timestamps": {
                "created_at": "2021-06-25T20:19:30.307Z",
                "updated_at": "2021-06-25T20:19:30.307Z"
            }
        }
    }
}
```
